from SAT_trivial import TrivialSATSolver
from SAT_backtracking import SAT_backtracking
from trivial_backtracker import TrivialBacktrackingSolver

DEFAULT_SOLVER = TrivialBacktrackingSolver
TrivialSATSolver
SAT_backtracking
TrivialBacktrackingSolver